# 端口配置
server:
  port: 9090
  tomcat:
    uri-encoding: utf-8

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/budai_web_data?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# mybatis文件绑定
mybatis:
  mapper-locations: classpath:mysql/*.xml
  # 控制台sql语句日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
